// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormgen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"menlo.ai/indigo-api-gateway/app/infrastructure/database/dbschema"
)

func newApiKey(db *gorm.DB, opts ...gen.DOOption) apiKey {
	_apiKey := apiKey{}

	_apiKey.apiKeyDo.UseDB(db, opts...)
	_apiKey.apiKeyDo.UseModel(&dbschema.ApiKey{})

	tableName := _apiKey.apiKeyDo.TableName()
	_apiKey.ALL = field.NewAsterisk(tableName)
	_apiKey.ID = field.NewUint(tableName, "id")
	_apiKey.CreatedAt = field.NewTime(tableName, "created_at")
	_apiKey.UpdatedAt = field.NewTime(tableName, "updated_at")
	_apiKey.DeletedAt = field.NewField(tableName, "deleted_at")
	_apiKey.PublicID = field.NewString(tableName, "public_id")
	_apiKey.KeyHash = field.NewString(tableName, "key_hash")
	_apiKey.PlaintextHint = field.NewString(tableName, "plaintext_hint")
	_apiKey.Description = field.NewString(tableName, "description")
	_apiKey.Enabled = field.NewBool(tableName, "enabled")
	_apiKey.ApikeyType = field.NewString(tableName, "apikey_type")
	_apiKey.OwnerPublicID = field.NewString(tableName, "owner_public_id")
	_apiKey.OrganizationID = field.NewUint(tableName, "organization_id")
	_apiKey.ProjectID = field.NewUint(tableName, "project_id")
	_apiKey.Permissions = field.NewString(tableName, "permissions")
	_apiKey.ExpiresAt = field.NewTime(tableName, "expires_at")
	_apiKey.LastUsedAt = field.NewTime(tableName, "last_used_at")

	_apiKey.fillFieldMap()

	return _apiKey
}

type apiKey struct {
	apiKeyDo

	ALL            field.Asterisk
	ID             field.Uint
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field
	PublicID       field.String
	KeyHash        field.String
	PlaintextHint  field.String
	Description    field.String
	Enabled        field.Bool
	ApikeyType     field.String
	OwnerPublicID  field.String
	OrganizationID field.Uint
	ProjectID      field.Uint
	Permissions    field.String
	ExpiresAt      field.Time
	LastUsedAt     field.Time

	fieldMap map[string]field.Expr
}

func (a apiKey) Table(newTableName string) *apiKey {
	a.apiKeyDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a apiKey) As(alias string) *apiKey {
	a.apiKeyDo.DO = *(a.apiKeyDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *apiKey) updateTableName(table string) *apiKey {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.PublicID = field.NewString(table, "public_id")
	a.KeyHash = field.NewString(table, "key_hash")
	a.PlaintextHint = field.NewString(table, "plaintext_hint")
	a.Description = field.NewString(table, "description")
	a.Enabled = field.NewBool(table, "enabled")
	a.ApikeyType = field.NewString(table, "apikey_type")
	a.OwnerPublicID = field.NewString(table, "owner_public_id")
	a.OrganizationID = field.NewUint(table, "organization_id")
	a.ProjectID = field.NewUint(table, "project_id")
	a.Permissions = field.NewString(table, "permissions")
	a.ExpiresAt = field.NewTime(table, "expires_at")
	a.LastUsedAt = field.NewTime(table, "last_used_at")

	a.fillFieldMap()

	return a
}

func (a *apiKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *apiKey) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 16)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["public_id"] = a.PublicID
	a.fieldMap["key_hash"] = a.KeyHash
	a.fieldMap["plaintext_hint"] = a.PlaintextHint
	a.fieldMap["description"] = a.Description
	a.fieldMap["enabled"] = a.Enabled
	a.fieldMap["apikey_type"] = a.ApikeyType
	a.fieldMap["owner_public_id"] = a.OwnerPublicID
	a.fieldMap["organization_id"] = a.OrganizationID
	a.fieldMap["project_id"] = a.ProjectID
	a.fieldMap["permissions"] = a.Permissions
	a.fieldMap["expires_at"] = a.ExpiresAt
	a.fieldMap["last_used_at"] = a.LastUsedAt
}

func (a apiKey) clone(db *gorm.DB) apiKey {
	a.apiKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a apiKey) replaceDB(db *gorm.DB) apiKey {
	a.apiKeyDo.ReplaceDB(db)
	return a
}

type apiKeyDo struct{ gen.DO }

type IApiKeyDo interface {
	gen.SubQuery
	Debug() IApiKeyDo
	WithContext(ctx context.Context) IApiKeyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IApiKeyDo
	WriteDB() IApiKeyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IApiKeyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IApiKeyDo
	Not(conds ...gen.Condition) IApiKeyDo
	Or(conds ...gen.Condition) IApiKeyDo
	Select(conds ...field.Expr) IApiKeyDo
	Where(conds ...gen.Condition) IApiKeyDo
	Order(conds ...field.Expr) IApiKeyDo
	Distinct(cols ...field.Expr) IApiKeyDo
	Omit(cols ...field.Expr) IApiKeyDo
	Join(table schema.Tabler, on ...field.Expr) IApiKeyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IApiKeyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IApiKeyDo
	Group(cols ...field.Expr) IApiKeyDo
	Having(conds ...gen.Condition) IApiKeyDo
	Limit(limit int) IApiKeyDo
	Offset(offset int) IApiKeyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IApiKeyDo
	Unscoped() IApiKeyDo
	Create(values ...*dbschema.ApiKey) error
	CreateInBatches(values []*dbschema.ApiKey, batchSize int) error
	Save(values ...*dbschema.ApiKey) error
	First() (*dbschema.ApiKey, error)
	Take() (*dbschema.ApiKey, error)
	Last() (*dbschema.ApiKey, error)
	Find() ([]*dbschema.ApiKey, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.ApiKey, err error)
	FindInBatches(result *[]*dbschema.ApiKey, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*dbschema.ApiKey) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IApiKeyDo
	Assign(attrs ...field.AssignExpr) IApiKeyDo
	Joins(fields ...field.RelationField) IApiKeyDo
	Preload(fields ...field.RelationField) IApiKeyDo
	FirstOrInit() (*dbschema.ApiKey, error)
	FirstOrCreate() (*dbschema.ApiKey, error)
	FindByPage(offset int, limit int) (result []*dbschema.ApiKey, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IApiKeyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a apiKeyDo) Debug() IApiKeyDo {
	return a.withDO(a.DO.Debug())
}

func (a apiKeyDo) WithContext(ctx context.Context) IApiKeyDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a apiKeyDo) ReadDB() IApiKeyDo {
	return a.Clauses(dbresolver.Read)
}

func (a apiKeyDo) WriteDB() IApiKeyDo {
	return a.Clauses(dbresolver.Write)
}

func (a apiKeyDo) Session(config *gorm.Session) IApiKeyDo {
	return a.withDO(a.DO.Session(config))
}

func (a apiKeyDo) Clauses(conds ...clause.Expression) IApiKeyDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a apiKeyDo) Returning(value interface{}, columns ...string) IApiKeyDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a apiKeyDo) Not(conds ...gen.Condition) IApiKeyDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a apiKeyDo) Or(conds ...gen.Condition) IApiKeyDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a apiKeyDo) Select(conds ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a apiKeyDo) Where(conds ...gen.Condition) IApiKeyDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a apiKeyDo) Order(conds ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a apiKeyDo) Distinct(cols ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a apiKeyDo) Omit(cols ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a apiKeyDo) Join(table schema.Tabler, on ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a apiKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a apiKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a apiKeyDo) Group(cols ...field.Expr) IApiKeyDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a apiKeyDo) Having(conds ...gen.Condition) IApiKeyDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a apiKeyDo) Limit(limit int) IApiKeyDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a apiKeyDo) Offset(offset int) IApiKeyDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a apiKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IApiKeyDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a apiKeyDo) Unscoped() IApiKeyDo {
	return a.withDO(a.DO.Unscoped())
}

func (a apiKeyDo) Create(values ...*dbschema.ApiKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a apiKeyDo) CreateInBatches(values []*dbschema.ApiKey, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a apiKeyDo) Save(values ...*dbschema.ApiKey) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a apiKeyDo) First() (*dbschema.ApiKey, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ApiKey), nil
	}
}

func (a apiKeyDo) Take() (*dbschema.ApiKey, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ApiKey), nil
	}
}

func (a apiKeyDo) Last() (*dbschema.ApiKey, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ApiKey), nil
	}
}

func (a apiKeyDo) Find() ([]*dbschema.ApiKey, error) {
	result, err := a.DO.Find()
	return result.([]*dbschema.ApiKey), err
}

func (a apiKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.ApiKey, err error) {
	buf := make([]*dbschema.ApiKey, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a apiKeyDo) FindInBatches(result *[]*dbschema.ApiKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a apiKeyDo) Attrs(attrs ...field.AssignExpr) IApiKeyDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a apiKeyDo) Assign(attrs ...field.AssignExpr) IApiKeyDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a apiKeyDo) Joins(fields ...field.RelationField) IApiKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a apiKeyDo) Preload(fields ...field.RelationField) IApiKeyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a apiKeyDo) FirstOrInit() (*dbschema.ApiKey, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ApiKey), nil
	}
}

func (a apiKeyDo) FirstOrCreate() (*dbschema.ApiKey, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ApiKey), nil
	}
}

func (a apiKeyDo) FindByPage(offset int, limit int) (result []*dbschema.ApiKey, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a apiKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a apiKeyDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a apiKeyDo) Delete(models ...*dbschema.ApiKey) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *apiKeyDo) withDO(do gen.Dao) *apiKeyDo {
	a.DO = *do.(*gen.DO)
	return a
}
