// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormgen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"menlo.ai/indigo-api-gateway/app/infrastructure/database/dbschema"
)

func newConversation(db *gorm.DB, opts ...gen.DOOption) conversation {
	_conversation := conversation{}

	_conversation.conversationDo.UseDB(db, opts...)
	_conversation.conversationDo.UseModel(&dbschema.Conversation{})

	tableName := _conversation.conversationDo.TableName()
	_conversation.ALL = field.NewAsterisk(tableName)
	_conversation.ID = field.NewUint(tableName, "id")
	_conversation.CreatedAt = field.NewTime(tableName, "created_at")
	_conversation.UpdatedAt = field.NewTime(tableName, "updated_at")
	_conversation.DeletedAt = field.NewField(tableName, "deleted_at")
	_conversation.PublicID = field.NewString(tableName, "public_id")
	_conversation.Title = field.NewString(tableName, "title")
	_conversation.UserID = field.NewUint(tableName, "user_id")
	_conversation.WorkspacePublicID = field.NewString(tableName, "workspace_public_id")
	_conversation.Status = field.NewString(tableName, "status")
	_conversation.Metadata = field.NewString(tableName, "metadata")
	_conversation.IsPrivate = field.NewBool(tableName, "is_private")
	_conversation.Items = conversationHasManyItems{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Items", "dbschema.Item"),
		Conversation: struct {
			field.RelationField
			User struct {
				field.RelationField
				Organizations struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
			}
			Workspace struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Conversations struct {
					field.RelationField
				}
			}
			Items struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Items.Conversation", "dbschema.Conversation"),
			User: struct {
				field.RelationField
				Organizations struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Items.Conversation.User", "dbschema.User"),
				Organizations: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Items.Conversation.User.Organizations", "dbschema.OrganizationMember"),
				},
				Projects: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Items.Conversation.User.Projects", "dbschema.ProjectMember"),
				},
			},
			Workspace: struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Conversations struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Items.Conversation.Workspace", "dbschema.Workspace"),
				User: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Items.Conversation.Workspace.User", "dbschema.User"),
				},
				Conversations: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Items.Conversation.Workspace.Conversations", "dbschema.Conversation"),
				},
			},
			Items: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Items.Conversation.Items", "dbschema.Item"),
			},
		},
		Response: struct {
			field.RelationField
			UserEntity struct {
				field.RelationField
			}
			Conversation struct {
				field.RelationField
			}
			Items struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Items.Response", "dbschema.Response"),
			UserEntity: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Items.Response.UserEntity", "dbschema.User"),
			},
			Conversation: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Items.Response.Conversation", "dbschema.Conversation"),
			},
			Items: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Items.Response.Items", "dbschema.Item"),
			},
		},
	}

	_conversation.User = conversationBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "dbschema.User"),
	}

	_conversation.Workspace = conversationBelongsToWorkspace{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Workspace", "dbschema.Workspace"),
	}

	_conversation.fillFieldMap()

	return _conversation
}

type conversation struct {
	conversationDo

	ALL               field.Asterisk
	ID                field.Uint
	CreatedAt         field.Time
	UpdatedAt         field.Time
	DeletedAt         field.Field
	PublicID          field.String
	Title             field.String
	UserID            field.Uint
	WorkspacePublicID field.String
	Status            field.String
	Metadata          field.String
	IsPrivate         field.Bool
	Items             conversationHasManyItems

	User conversationBelongsToUser

	Workspace conversationBelongsToWorkspace

	fieldMap map[string]field.Expr
}

func (c conversation) Table(newTableName string) *conversation {
	c.conversationDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c conversation) As(alias string) *conversation {
	c.conversationDo.DO = *(c.conversationDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *conversation) updateTableName(table string) *conversation {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.PublicID = field.NewString(table, "public_id")
	c.Title = field.NewString(table, "title")
	c.UserID = field.NewUint(table, "user_id")
	c.WorkspacePublicID = field.NewString(table, "workspace_public_id")
	c.Status = field.NewString(table, "status")
	c.Metadata = field.NewString(table, "metadata")
	c.IsPrivate = field.NewBool(table, "is_private")

	c.fillFieldMap()

	return c
}

func (c *conversation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *conversation) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 14)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["public_id"] = c.PublicID
	c.fieldMap["title"] = c.Title
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["workspace_public_id"] = c.WorkspacePublicID
	c.fieldMap["status"] = c.Status
	c.fieldMap["metadata"] = c.Metadata
	c.fieldMap["is_private"] = c.IsPrivate

}

func (c conversation) clone(db *gorm.DB) conversation {
	c.conversationDo.ReplaceConnPool(db.Statement.ConnPool)
	c.Items.db = db.Session(&gorm.Session{Initialized: true})
	c.Items.db.Statement.ConnPool = db.Statement.ConnPool
	c.User.db = db.Session(&gorm.Session{Initialized: true})
	c.User.db.Statement.ConnPool = db.Statement.ConnPool
	c.Workspace.db = db.Session(&gorm.Session{Initialized: true})
	c.Workspace.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c conversation) replaceDB(db *gorm.DB) conversation {
	c.conversationDo.ReplaceDB(db)
	c.Items.db = db.Session(&gorm.Session{})
	c.User.db = db.Session(&gorm.Session{})
	c.Workspace.db = db.Session(&gorm.Session{})
	return c
}

type conversationHasManyItems struct {
	db *gorm.DB

	field.RelationField

	Conversation struct {
		field.RelationField
		User struct {
			field.RelationField
			Organizations struct {
				field.RelationField
			}
			Projects struct {
				field.RelationField
			}
		}
		Workspace struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Conversations struct {
				field.RelationField
			}
		}
		Items struct {
			field.RelationField
		}
	}
	Response struct {
		field.RelationField
		UserEntity struct {
			field.RelationField
		}
		Conversation struct {
			field.RelationField
		}
		Items struct {
			field.RelationField
		}
	}
}

func (a conversationHasManyItems) Where(conds ...field.Expr) *conversationHasManyItems {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a conversationHasManyItems) WithContext(ctx context.Context) *conversationHasManyItems {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a conversationHasManyItems) Session(session *gorm.Session) *conversationHasManyItems {
	a.db = a.db.Session(session)
	return &a
}

func (a conversationHasManyItems) Model(m *dbschema.Conversation) *conversationHasManyItemsTx {
	return &conversationHasManyItemsTx{a.db.Model(m).Association(a.Name())}
}

func (a conversationHasManyItems) Unscoped() *conversationHasManyItems {
	a.db = a.db.Unscoped()
	return &a
}

type conversationHasManyItemsTx struct{ tx *gorm.Association }

func (a conversationHasManyItemsTx) Find() (result []*dbschema.Item, err error) {
	return result, a.tx.Find(&result)
}

func (a conversationHasManyItemsTx) Append(values ...*dbschema.Item) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a conversationHasManyItemsTx) Replace(values ...*dbschema.Item) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a conversationHasManyItemsTx) Delete(values ...*dbschema.Item) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a conversationHasManyItemsTx) Clear() error {
	return a.tx.Clear()
}

func (a conversationHasManyItemsTx) Count() int64 {
	return a.tx.Count()
}

func (a conversationHasManyItemsTx) Unscoped() *conversationHasManyItemsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type conversationBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a conversationBelongsToUser) Where(conds ...field.Expr) *conversationBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a conversationBelongsToUser) WithContext(ctx context.Context) *conversationBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a conversationBelongsToUser) Session(session *gorm.Session) *conversationBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a conversationBelongsToUser) Model(m *dbschema.Conversation) *conversationBelongsToUserTx {
	return &conversationBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a conversationBelongsToUser) Unscoped() *conversationBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type conversationBelongsToUserTx struct{ tx *gorm.Association }

func (a conversationBelongsToUserTx) Find() (result *dbschema.User, err error) {
	return result, a.tx.Find(&result)
}

func (a conversationBelongsToUserTx) Append(values ...*dbschema.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a conversationBelongsToUserTx) Replace(values ...*dbschema.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a conversationBelongsToUserTx) Delete(values ...*dbschema.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a conversationBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a conversationBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a conversationBelongsToUserTx) Unscoped() *conversationBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type conversationBelongsToWorkspace struct {
	db *gorm.DB

	field.RelationField
}

func (a conversationBelongsToWorkspace) Where(conds ...field.Expr) *conversationBelongsToWorkspace {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a conversationBelongsToWorkspace) WithContext(ctx context.Context) *conversationBelongsToWorkspace {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a conversationBelongsToWorkspace) Session(session *gorm.Session) *conversationBelongsToWorkspace {
	a.db = a.db.Session(session)
	return &a
}

func (a conversationBelongsToWorkspace) Model(m *dbschema.Conversation) *conversationBelongsToWorkspaceTx {
	return &conversationBelongsToWorkspaceTx{a.db.Model(m).Association(a.Name())}
}

func (a conversationBelongsToWorkspace) Unscoped() *conversationBelongsToWorkspace {
	a.db = a.db.Unscoped()
	return &a
}

type conversationBelongsToWorkspaceTx struct{ tx *gorm.Association }

func (a conversationBelongsToWorkspaceTx) Find() (result *dbschema.Workspace, err error) {
	return result, a.tx.Find(&result)
}

func (a conversationBelongsToWorkspaceTx) Append(values ...*dbschema.Workspace) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a conversationBelongsToWorkspaceTx) Replace(values ...*dbschema.Workspace) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a conversationBelongsToWorkspaceTx) Delete(values ...*dbschema.Workspace) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a conversationBelongsToWorkspaceTx) Clear() error {
	return a.tx.Clear()
}

func (a conversationBelongsToWorkspaceTx) Count() int64 {
	return a.tx.Count()
}

func (a conversationBelongsToWorkspaceTx) Unscoped() *conversationBelongsToWorkspaceTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type conversationDo struct{ gen.DO }

type IConversationDo interface {
	gen.SubQuery
	Debug() IConversationDo
	WithContext(ctx context.Context) IConversationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConversationDo
	WriteDB() IConversationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConversationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConversationDo
	Not(conds ...gen.Condition) IConversationDo
	Or(conds ...gen.Condition) IConversationDo
	Select(conds ...field.Expr) IConversationDo
	Where(conds ...gen.Condition) IConversationDo
	Order(conds ...field.Expr) IConversationDo
	Distinct(cols ...field.Expr) IConversationDo
	Omit(cols ...field.Expr) IConversationDo
	Join(table schema.Tabler, on ...field.Expr) IConversationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConversationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConversationDo
	Group(cols ...field.Expr) IConversationDo
	Having(conds ...gen.Condition) IConversationDo
	Limit(limit int) IConversationDo
	Offset(offset int) IConversationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConversationDo
	Unscoped() IConversationDo
	Create(values ...*dbschema.Conversation) error
	CreateInBatches(values []*dbschema.Conversation, batchSize int) error
	Save(values ...*dbschema.Conversation) error
	First() (*dbschema.Conversation, error)
	Take() (*dbschema.Conversation, error)
	Last() (*dbschema.Conversation, error)
	Find() ([]*dbschema.Conversation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.Conversation, err error)
	FindInBatches(result *[]*dbschema.Conversation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*dbschema.Conversation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConversationDo
	Assign(attrs ...field.AssignExpr) IConversationDo
	Joins(fields ...field.RelationField) IConversationDo
	Preload(fields ...field.RelationField) IConversationDo
	FirstOrInit() (*dbschema.Conversation, error)
	FirstOrCreate() (*dbschema.Conversation, error)
	FindByPage(offset int, limit int) (result []*dbschema.Conversation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConversationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c conversationDo) Debug() IConversationDo {
	return c.withDO(c.DO.Debug())
}

func (c conversationDo) WithContext(ctx context.Context) IConversationDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c conversationDo) ReadDB() IConversationDo {
	return c.Clauses(dbresolver.Read)
}

func (c conversationDo) WriteDB() IConversationDo {
	return c.Clauses(dbresolver.Write)
}

func (c conversationDo) Session(config *gorm.Session) IConversationDo {
	return c.withDO(c.DO.Session(config))
}

func (c conversationDo) Clauses(conds ...clause.Expression) IConversationDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c conversationDo) Returning(value interface{}, columns ...string) IConversationDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c conversationDo) Not(conds ...gen.Condition) IConversationDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c conversationDo) Or(conds ...gen.Condition) IConversationDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c conversationDo) Select(conds ...field.Expr) IConversationDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c conversationDo) Where(conds ...gen.Condition) IConversationDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c conversationDo) Order(conds ...field.Expr) IConversationDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c conversationDo) Distinct(cols ...field.Expr) IConversationDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c conversationDo) Omit(cols ...field.Expr) IConversationDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c conversationDo) Join(table schema.Tabler, on ...field.Expr) IConversationDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c conversationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConversationDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c conversationDo) RightJoin(table schema.Tabler, on ...field.Expr) IConversationDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c conversationDo) Group(cols ...field.Expr) IConversationDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c conversationDo) Having(conds ...gen.Condition) IConversationDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c conversationDo) Limit(limit int) IConversationDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c conversationDo) Offset(offset int) IConversationDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c conversationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConversationDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c conversationDo) Unscoped() IConversationDo {
	return c.withDO(c.DO.Unscoped())
}

func (c conversationDo) Create(values ...*dbschema.Conversation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c conversationDo) CreateInBatches(values []*dbschema.Conversation, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c conversationDo) Save(values ...*dbschema.Conversation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c conversationDo) First() (*dbschema.Conversation, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.Conversation), nil
	}
}

func (c conversationDo) Take() (*dbschema.Conversation, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.Conversation), nil
	}
}

func (c conversationDo) Last() (*dbschema.Conversation, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.Conversation), nil
	}
}

func (c conversationDo) Find() ([]*dbschema.Conversation, error) {
	result, err := c.DO.Find()
	return result.([]*dbschema.Conversation), err
}

func (c conversationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.Conversation, err error) {
	buf := make([]*dbschema.Conversation, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c conversationDo) FindInBatches(result *[]*dbschema.Conversation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c conversationDo) Attrs(attrs ...field.AssignExpr) IConversationDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c conversationDo) Assign(attrs ...field.AssignExpr) IConversationDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c conversationDo) Joins(fields ...field.RelationField) IConversationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c conversationDo) Preload(fields ...field.RelationField) IConversationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c conversationDo) FirstOrInit() (*dbschema.Conversation, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.Conversation), nil
	}
}

func (c conversationDo) FirstOrCreate() (*dbschema.Conversation, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.Conversation), nil
	}
}

func (c conversationDo) FindByPage(offset int, limit int) (result []*dbschema.Conversation, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c conversationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c conversationDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c conversationDo) Delete(models ...*dbschema.Conversation) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *conversationDo) withDO(do gen.Dao) *conversationDo {
	c.DO = *do.(*gen.DO)
	return c
}
