// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormgen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"menlo.ai/indigo-api-gateway/app/infrastructure/database/dbschema"
)

func newOrganization(db *gorm.DB, opts ...gen.DOOption) organization {
	_organization := organization{}

	_organization.organizationDo.UseDB(db, opts...)
	_organization.organizationDo.UseModel(&dbschema.Organization{})

	tableName := _organization.organizationDo.TableName()
	_organization.ALL = field.NewAsterisk(tableName)
	_organization.ID = field.NewUint(tableName, "id")
	_organization.CreatedAt = field.NewTime(tableName, "created_at")
	_organization.UpdatedAt = field.NewTime(tableName, "updated_at")
	_organization.DeletedAt = field.NewField(tableName, "deleted_at")
	_organization.Name = field.NewString(tableName, "name")
	_organization.PublicID = field.NewString(tableName, "public_id")
	_organization.Enabled = field.NewBool(tableName, "enabled")
	_organization.Members = organizationHasManyMembers{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Members", "dbschema.OrganizationMember"),
	}

	_organization.fillFieldMap()

	return _organization
}

type organization struct {
	organizationDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Name      field.String
	PublicID  field.String
	Enabled   field.Bool
	Members   organizationHasManyMembers

	fieldMap map[string]field.Expr
}

func (o organization) Table(newTableName string) *organization {
	o.organizationDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o organization) As(alias string) *organization {
	o.organizationDo.DO = *(o.organizationDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *organization) updateTableName(table string) *organization {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewUint(table, "id")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.DeletedAt = field.NewField(table, "deleted_at")
	o.Name = field.NewString(table, "name")
	o.PublicID = field.NewString(table, "public_id")
	o.Enabled = field.NewBool(table, "enabled")

	o.fillFieldMap()

	return o
}

func (o *organization) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *organization) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 8)
	o.fieldMap["id"] = o.ID
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["deleted_at"] = o.DeletedAt
	o.fieldMap["name"] = o.Name
	o.fieldMap["public_id"] = o.PublicID
	o.fieldMap["enabled"] = o.Enabled

}

func (o organization) clone(db *gorm.DB) organization {
	o.organizationDo.ReplaceConnPool(db.Statement.ConnPool)
	o.Members.db = db.Session(&gorm.Session{Initialized: true})
	o.Members.db.Statement.ConnPool = db.Statement.ConnPool
	return o
}

func (o organization) replaceDB(db *gorm.DB) organization {
	o.organizationDo.ReplaceDB(db)
	o.Members.db = db.Session(&gorm.Session{})
	return o
}

type organizationHasManyMembers struct {
	db *gorm.DB

	field.RelationField
}

func (a organizationHasManyMembers) Where(conds ...field.Expr) *organizationHasManyMembers {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a organizationHasManyMembers) WithContext(ctx context.Context) *organizationHasManyMembers {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a organizationHasManyMembers) Session(session *gorm.Session) *organizationHasManyMembers {
	a.db = a.db.Session(session)
	return &a
}

func (a organizationHasManyMembers) Model(m *dbschema.Organization) *organizationHasManyMembersTx {
	return &organizationHasManyMembersTx{a.db.Model(m).Association(a.Name())}
}

func (a organizationHasManyMembers) Unscoped() *organizationHasManyMembers {
	a.db = a.db.Unscoped()
	return &a
}

type organizationHasManyMembersTx struct{ tx *gorm.Association }

func (a organizationHasManyMembersTx) Find() (result []*dbschema.OrganizationMember, err error) {
	return result, a.tx.Find(&result)
}

func (a organizationHasManyMembersTx) Append(values ...*dbschema.OrganizationMember) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a organizationHasManyMembersTx) Replace(values ...*dbschema.OrganizationMember) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a organizationHasManyMembersTx) Delete(values ...*dbschema.OrganizationMember) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a organizationHasManyMembersTx) Clear() error {
	return a.tx.Clear()
}

func (a organizationHasManyMembersTx) Count() int64 {
	return a.tx.Count()
}

func (a organizationHasManyMembersTx) Unscoped() *organizationHasManyMembersTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type organizationDo struct{ gen.DO }

type IOrganizationDo interface {
	gen.SubQuery
	Debug() IOrganizationDo
	WithContext(ctx context.Context) IOrganizationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOrganizationDo
	WriteDB() IOrganizationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOrganizationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOrganizationDo
	Not(conds ...gen.Condition) IOrganizationDo
	Or(conds ...gen.Condition) IOrganizationDo
	Select(conds ...field.Expr) IOrganizationDo
	Where(conds ...gen.Condition) IOrganizationDo
	Order(conds ...field.Expr) IOrganizationDo
	Distinct(cols ...field.Expr) IOrganizationDo
	Omit(cols ...field.Expr) IOrganizationDo
	Join(table schema.Tabler, on ...field.Expr) IOrganizationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOrganizationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOrganizationDo
	Group(cols ...field.Expr) IOrganizationDo
	Having(conds ...gen.Condition) IOrganizationDo
	Limit(limit int) IOrganizationDo
	Offset(offset int) IOrganizationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOrganizationDo
	Unscoped() IOrganizationDo
	Create(values ...*dbschema.Organization) error
	CreateInBatches(values []*dbschema.Organization, batchSize int) error
	Save(values ...*dbschema.Organization) error
	First() (*dbschema.Organization, error)
	Take() (*dbschema.Organization, error)
	Last() (*dbschema.Organization, error)
	Find() ([]*dbschema.Organization, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.Organization, err error)
	FindInBatches(result *[]*dbschema.Organization, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*dbschema.Organization) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOrganizationDo
	Assign(attrs ...field.AssignExpr) IOrganizationDo
	Joins(fields ...field.RelationField) IOrganizationDo
	Preload(fields ...field.RelationField) IOrganizationDo
	FirstOrInit() (*dbschema.Organization, error)
	FirstOrCreate() (*dbschema.Organization, error)
	FindByPage(offset int, limit int) (result []*dbschema.Organization, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOrganizationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o organizationDo) Debug() IOrganizationDo {
	return o.withDO(o.DO.Debug())
}

func (o organizationDo) WithContext(ctx context.Context) IOrganizationDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o organizationDo) ReadDB() IOrganizationDo {
	return o.Clauses(dbresolver.Read)
}

func (o organizationDo) WriteDB() IOrganizationDo {
	return o.Clauses(dbresolver.Write)
}

func (o organizationDo) Session(config *gorm.Session) IOrganizationDo {
	return o.withDO(o.DO.Session(config))
}

func (o organizationDo) Clauses(conds ...clause.Expression) IOrganizationDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o organizationDo) Returning(value interface{}, columns ...string) IOrganizationDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o organizationDo) Not(conds ...gen.Condition) IOrganizationDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o organizationDo) Or(conds ...gen.Condition) IOrganizationDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o organizationDo) Select(conds ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o organizationDo) Where(conds ...gen.Condition) IOrganizationDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o organizationDo) Order(conds ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o organizationDo) Distinct(cols ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o organizationDo) Omit(cols ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o organizationDo) Join(table schema.Tabler, on ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o organizationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o organizationDo) RightJoin(table schema.Tabler, on ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o organizationDo) Group(cols ...field.Expr) IOrganizationDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o organizationDo) Having(conds ...gen.Condition) IOrganizationDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o organizationDo) Limit(limit int) IOrganizationDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o organizationDo) Offset(offset int) IOrganizationDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o organizationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOrganizationDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o organizationDo) Unscoped() IOrganizationDo {
	return o.withDO(o.DO.Unscoped())
}

func (o organizationDo) Create(values ...*dbschema.Organization) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o organizationDo) CreateInBatches(values []*dbschema.Organization, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o organizationDo) Save(values ...*dbschema.Organization) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o organizationDo) First() (*dbschema.Organization, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.Organization), nil
	}
}

func (o organizationDo) Take() (*dbschema.Organization, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.Organization), nil
	}
}

func (o organizationDo) Last() (*dbschema.Organization, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.Organization), nil
	}
}

func (o organizationDo) Find() ([]*dbschema.Organization, error) {
	result, err := o.DO.Find()
	return result.([]*dbschema.Organization), err
}

func (o organizationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.Organization, err error) {
	buf := make([]*dbschema.Organization, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o organizationDo) FindInBatches(result *[]*dbschema.Organization, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o organizationDo) Attrs(attrs ...field.AssignExpr) IOrganizationDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o organizationDo) Assign(attrs ...field.AssignExpr) IOrganizationDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o organizationDo) Joins(fields ...field.RelationField) IOrganizationDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o organizationDo) Preload(fields ...field.RelationField) IOrganizationDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o organizationDo) FirstOrInit() (*dbschema.Organization, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.Organization), nil
	}
}

func (o organizationDo) FirstOrCreate() (*dbschema.Organization, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.Organization), nil
	}
}

func (o organizationDo) FindByPage(offset int, limit int) (result []*dbschema.Organization, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o organizationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o organizationDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o organizationDo) Delete(models ...*dbschema.Organization) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *organizationDo) withDO(do gen.Dao) *organizationDo {
	o.DO = *do.(*gen.DO)
	return o
}
